// Static placeholder content used until the Neon database has been seeded.
// The site prefers the database (see db.ts + world-data.server.ts) and only
// falls back to this bundled data when DATABASE_URL is missing or unreachable.

import birth from "@/assets/memory-birth.jpg";
import birthday from "@/assets/memory-birthday.jpg";
import smile from "@/assets/memory-smile.jpg";
import steps from "@/assets/memory-steps.jpg";

export const placeholderChild = {
  name: "Tamim",
  birthdate: "2024-03-18",
  welcome: "A little corner of the world where we keep the moments that make our hearts feel full.",
};

export const placeholderMemories = [
  {
    id: "birth",
    title: "The day you arrived",
    date: "March 18, 2024",
    category: "Milestones",
    image: birth,
    excerpt: "The whole room grew quiet, and then there you were.",
    story:
      "We counted every tiny finger and toe. You opened your eyes, held one of our fingers, and made the world feel completely new.",
    sort_order: 1,
  },
  {
    id: "smile",
    title: "Your first big smile",
    date: "May 27, 2024",
    category: "Everyday moments",
    image: smile,
    excerpt: "A sleepy morning suddenly became unforgettable.",
    story:
      "Sunlight came through the nursery window and you gave us the widest, happiest smile. We laughed, then you laughed too.",
    sort_order: 2,
  },
  {
    id: "steps",
    title: "Three brave little steps",
    date: "February 2, 2025",
    category: "Milestones",
    image: steps,
    excerpt: "You let go, wobbled, and walked right into our arms.",
    story:
      "Nobody breathed for those few seconds. You looked so proud when you reached us, and immediately turned around to try again.",
    sort_order: 3,
  },
  {
    id: "birthday",
    title: "One whole year of you",
    date: "March 18, 2025",
    category: "Celebrations",
    image: birthday,
    excerpt: "One candle, many happy tears, and cake everywhere.",
    story:
      "The people who love you filled the room. You were far more interested in the cake than the candle—and we wouldn't have it any other way.",
    sort_order: 4,
  },
];

export const placeholderRelatives = [
  // ---- Parents ----
  {
    id: "momen",
    name: "مؤمن",
    relationship: "بابا",
    group: "Parents",
    image: steps,
    fact: "بيحب الضحك مع تميم كل يوم.",
    bio: "بابا تميم ورفيقه الأول في كل مغامرة وعند لعب.",
    sort_order: 1,
  },
  {
    id: "nagham",
    name: "نغم",
    relationship: "ماما",
    group: "Parents",
    image: smile,
    fact: "بتغني له أجمل أغاني النوم.",
    bio: "ماما تميم، وحضنها هو المكان الأأمن في الدنيا.",
    sort_order: 2,
  },

  // ---- Grandparents ----
  {
    id: "geddo-ahmed",
    name: "أحمد اللبان",
    relationship: "الجد (والد بابا)",
    group: "Grandparents",
    image: birth,
    fact: "بيحب كل مناسبة مع الأحفاد.",
    bio: "جد تميم من ناحية بابا، صاحب القلب الكبير.",
    sort_order: 3,
  },
  {
    id: "teta-nadia",
    name: "ناديه نايل",
    relationship: "الجدة (والدة بابا)",
    group: "Grandparents",
    image: birthday,
    fact: "دائمًا بتفتكر كلام حلو يقوله لتميم.",
    bio: "جدة تميم من ناحية بابا، وحكاياتها أحلى حكاية.",
    sort_order: 4,
  },
  {
    id: "geddo-ishaq",
    name: "أحمد اسحاق",
    relationship: "الجد (والد ماما)",
    group: "Grandparents",
    image: smile,
    fact: "دائمًا بيسأل عن تميم.",
    bio: "جد تميم من ناحية ماما.",
    sort_order: 5,
  },
  {
    id: "teta-magda",
    name: "ماجده بدر",
    relationship: "الجدة (والدة ماما)",
    group: "Grandparents",
    image: steps,
    fact: "بتعمل أحلى حلويات.",
    bio: "جدة تميم من ناحية ماما، وضحكتها بتحلّي الدنيا.",
    sort_order: 6,
  },

  // ---- Aunts & Uncles (direct) ----
  {
    id: "uncle-mody",
    name: "محمد «مودى»",
    relationship: "العم (شقيق بابا)",
    group: "Aunts & Uncles",
    image: birth,
    fact: "عنده مودى وزين.",
    bio: "عم تميم، ودايمًا بيجيبه هدية.",
    sort_order: 7,
  },
  {
    id: "aunt-aya",
    name: "ايه",
    relationship: "زوجة العم",
    group: "Aunts & Uncles",
    image: steps,
    fact: "أم مودى وزين.",
    bio: "زوجة العم مودى، وبيتها دايماً مليان ضحك.",
    sort_order: 8,
  },
  {
    id: "uncle-marwan",
    name: "مروان",
    relationship: "الخال (شقيق ماما)",
    group: "Aunts & Uncles",
    image: smile,
    fact: "بيحب يلعب مع تميم.",
    bio: "خال تميم، رفيق اللعب والمقالب.",
    sort_order: 9,
  },
  {
    id: "uncle-mohamed",
    name: "محمد",
    relationship: "الخال (شقيق ماما)",
    group: "Aunts & Uncles",
    image: birthday,
    fact: "خال تميم من ناحية ماما.",
    bio: "شقيق ماما، ودايمًا فاكر تميم.",
    sort_order: 10,
  },
  {
    id: "khala-tagrid",
    name: "تغريد",
    relationship: "الخالة (شقيقة ماما)",
    group: "Aunts & Uncles",
    image: birth,
    fact: "عندها بنت اسمها لمار.",
    bio: "شقيقة ماما، وضحكتهما مش بتخلص.",
    sort_order: 11,
  },
  {
    id: "uncle-maki",
    name: "أحمد مكى",
    relationship: "زوج الخالة",
    group: "Aunts & Uncles",
    image: steps,
    fact: "زوج الخالة تغريد.",
    bio: "أحمد مكى، زوج الخالة تغريد وأبو لمار.",
    sort_order: 12,
  },

  // ---- Cousins ----
  {
    id: "cousin-ahmed",
    name: "أحمد «مودى»",
    relationship: "ابن العم",
    group: "Cousins",
    image: smile,
    fact: "دلعه مودى.",
    bio: "ابن العم، من أولاد عم بابا مودى.",
    sort_order: 13,
  },
  {
    id: "cousin-zain",
    name: "زين",
    relationship: "ابن العم",
    group: "Cousins",
    image: birthday,
    fact: "ابن العم.",
    bio: "زين، أصغر أبناء العم مودى.",
    sort_order: 14,
  },
  {
    id: "cousin-lamar",
    name: "لمار",
    relationship: "بنت الخالة",
    group: "Cousins",
    image: birth,
    fact: "بنت الخالة تغريد.",
    bio: "لمار، بنت الخالة تغريد وأحمد مكى.",
    sort_order: 15,
  },

  // ---- Great aunts & uncles (paternal grandmother's side) ----
  {
    id: "khala-saad",
    name: "سعاد",
    relationship: "خالة بابا",
    group: "Great aunts & uncles",
    image: birthday,
    fact: "شقيقة الجدة ناديه.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 16,
  },
  {
    id: "khal-saeed",
    name: "سعيد",
    relationship: "خال بابا",
    group: "Great aunts & uncles",
    image: birth,
    fact: "شقيق الجدة ناديه.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 17,
  },
  {
    id: "khal-ali",
    name: "على",
    relationship: "خال بابا",
    group: "Great aunts & uncles",
    image: steps,
    fact: "شقيق الجدة ناديه.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 18,
  },
  {
    id: "khal-kamal",
    name: "كمال",
    relationship: "خال بابا",
    group: "Great aunts & uncles",
    image: smile,
    fact: "شقيق الجدة ناديه.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 19,
  },
  {
    id: "khal-hassan",
    name: "حسن",
    relationship: "خال بابا",
    group: "Great aunts & uncles",
    image: birthday,
    fact: "شقيق الجدة ناديه.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 20,
  },
  {
    id: "khala-anissa",
    name: "انيسه",
    relationship: "خالة بابا",
    group: "Great aunts & uncles",
    image: birth,
    fact: "شقيقة الجدة ناديه.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 21,
  },

  // ---- Great aunts & uncles (paternal grandfather's side) ----
  {
    id: "amt-hoda",
    name: "هدى",
    relationship: "عمة بابا",
    group: "Great aunts & uncles",
    image: steps,
    fact: "شقيقة الجد أحمد اللبان.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 22,
  },
  {
    id: "amt-nora",
    name: "نورا",
    relationship: "عمة بابا",
    group: "Great aunts & uncles",
    image: smile,
    fact: "شقيقة الجد أحمد اللبان.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 23,
  },
  {
    id: "am-hassan",
    name: "حسن",
    relationship: "عم بابا",
    group: "Great aunts & uncles",
    image: birthday,
    fact: "شقيق الجد أحمد اللبان.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 24,
  },
  {
    id: "am-gamal",
    name: "جمال",
    relationship: "عم بابا",
    group: "Great aunts & uncles",
    image: birth,
    fact: "شقيق الجد أحمد اللبان.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 25,
  },
  {
    id: "am-hamdy",
    name: "حمدى",
    relationship: "عم بابا",
    group: "Great aunts & uncles",
    image: steps,
    fact: "شقيق الجد أحمد اللبان.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 26,
  },

  // ---- Great aunts & uncles (maternal grandmother's side) ----
  {
    id: "khala-wafa",
    name: "وفاء",
    relationship: "خالة ماما",
    group: "Great aunts & uncles",
    image: smile,
    fact: "شقيقة الجدة ماجده.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 27,
  },
  {
    id: "khala-hoda",
    name: "هدى",
    relationship: "خالة ماما",
    group: "Great aunts & uncles",
    image: birthday,
    fact: "شقيقة الجدة ماجده.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 28,
  },
  {
    id: "khala-maha",
    name: "مها",
    relationship: "خالة ماما",
    group: "Great aunts & uncles",
    image: birth,
    fact: "شقيقة الجدة ماجده.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 29,
  },

  // ---- Great aunts & uncles (maternal grandfather's side) ----
  {
    id: "am-mohamed",
    name: "محمد",
    relationship: "عم ماما",
    group: "Great aunts & uncles",
    image: steps,
    fact: "شقيق الجد أحمد اسحاق.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 30,
  },
  {
    id: "am-hassan2",
    name: "حسن",
    relationship: "عم ماما",
    group: "Great aunts & uncles",
    image: birthday,
    fact: "شقيق الجد أحمد اسحاق.",
    bio: "من عائلة تميم الكبيرة الحبيبة.",
    sort_order: 31,
  },
];

export const placeholderLetters = [
  {
    id: "kind",
    title: "When the world asks you to be brave",
    author: "ماما",
    date: "For your 10th birthday",
    message:
      "My darling, courage is not about never feeling afraid. It is choosing kindness and taking one small step even when you are. You have carried that quiet courage since your very first steps.",
  },
  {
    id: "home",
    title: "Whenever you feel far from home",
    author: "بابا",
    date: "Open when you miss us",
    message:
      "Home is not only a place. It is every story we share, every laugh at the dinner table, and every person who knows the shape of your heart. You can always find your way back.",
  },
  {
    id: "dream",
    title: "On following a dream",
    author: "الجدة",
    date: "For the day you choose your path",
    message:
      "Take the path that leaves room for wonder. Work hard, stay gentle, and remember that becoming yourself is the most beautiful adventure of all.",
  },
];

export const placeholderProfiles = [
  { id: "family", name: "عائلة تميم", initials: "ت" },
  { id: "mama", name: "ماما نغم", initials: "ن" },
  { id: "baba", name: "بابا مؤمن", initials: "م" },
];
