/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamilyTreeRouteImport } from './routes/family-tree'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as RelativesRouteImport } from './routes/relatives'
import { Route as UnlockRouteImport } from './routes/unlock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyTreeRoute = FamilyTreeRouteImport.update({
  id: '/family-tree',
  path: '/family-tree',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const RelativesRoute = RelativesRouteImport.update({
  id: '/relatives',
  path: '/relatives',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/family-tree': typeof FamilyTreeRoute
  '/gallery': typeof GalleryRoute
  '/letters': typeof LettersRoute
  '/manage': typeof ManageRoute
  '/memories': typeof MemoriesRoute
  '/relatives': typeof RelativesRoute
  '/unlock': typeof UnlockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/family-tree': typeof FamilyTreeRoute
  '/gallery': typeof GalleryRoute
  '/letters': typeof LettersRoute
  '/manage': typeof ManageRoute
  '/memories': typeof MemoriesRoute
  '/relatives': typeof RelativesRoute
  '/unlock': typeof UnlockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/family-tree': typeof FamilyTreeRoute
  '/gallery': typeof GalleryRoute
  '/letters': typeof LettersRoute
  '/manage': typeof ManageRoute
  '/memories': typeof MemoriesRoute
  '/relatives': typeof RelativesRoute
  '/unlock': typeof UnlockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/family-tree'
    | '/gallery'
    | '/letters'
    | '/manage'
    | '/memories'
    | '/relatives'
    | '/unlock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/family-tree'
    | '/gallery'
    | '/letters'
    | '/manage'
    | '/memories'
    | '/relatives'
    | '/unlock'
  id:
    | '__root__'
    | '/'
    | '/family-tree'
    | '/gallery'
    | '/letters'
    | '/manage'
    | '/memories'
    | '/relatives'
    | '/unlock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FamilyTreeRoute: typeof FamilyTreeRoute
  GalleryRoute: typeof GalleryRoute
  LettersRoute: typeof LettersRoute
  ManageRoute: typeof ManageRoute
  MemoriesRoute: typeof MemoriesRoute
  RelativesRoute: typeof RelativesRoute
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-tree': {
      id: '/family-tree'
      path: '/family-tree'
      fullPath: '/family-tree'
      preLoaderRoute: typeof FamilyTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatives': {
      id: '/relatives'
      path: '/relatives'
      fullPath: '/relatives'
      preLoaderRoute: typeof RelativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FamilyTreeRoute: FamilyTreeRoute,
  GalleryRoute: GalleryRoute,
  LettersRoute: LettersRoute,
  ManageRoute: ManageRoute,
  MemoriesRoute: MemoriesRoute,
  RelativesRoute: RelativesRoute,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
